### ISSUE TITLE
fix unit-test 

### ISSUE THREAD

**Issue by lithqube** [elenaserezhkina/loginForm#1]
**Reproduction**:
by running the script ` yarn test` We get the following error:
```
 FAIL  src/App.test.js

Unable to find an element with the text: /learn react/i. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible....
```

**Acceptance criteria**: Unit-test should run without failures

**Comment by elenaserezhkina** [comment]
Hey, I have just changed the text in error messages so it matches the mockup. 
Could it be the reason why this text test failed?

**Comment by lithqube** [comment]
you can check on `jr/elenaserezhkina/src/App.test.js` for the necessary changes.  I recommend you to:
- [ ] create a new branch from master
- [ ] work on all the changes for that test to run successfully
- [ ] create a Pull Request 
Tomorrow we can review the changes during the presentation of the code, pls let me know if you need more info :)

**Comment by elenaserezhkina** [comment]
Ok, thank you! :)
